# Generated by Django 2.2.7 on 2019-11-29 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sobrevivente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome')),
                ('idade', models.IntegerField(blank=True, null=True, verbose_name='Idade')),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1, null=True, verbose_name='Sexo')),
                ('latitude', models.CharField(blank=True, max_length=10, null=True, verbose_name='Latitude')),
                ('longitude', models.CharField(blank=True, max_length=10, null=True, verbose_name='Latitude')),
            ],
        ),
    ]
