# Generated by Django 2.2.7 on 2019-12-01 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_inventario_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sobrevivente',
            name='latitude',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='sobrevivente',
            name='longitude',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Latitude'),
        ),
    ]
