# Generated by Django 2.2.7 on 2019-12-02 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191201_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='sobrevivente',
            name='infectado',
            field=models.BooleanField(default=False, verbose_name='Está infectado?'),
        ),
        migrations.AddField(
            model_name='sobrevivente',
            name='votos',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Votos'),
        ),
    ]
